site_name: Technical Documentation
site_dir: ../proactis-documentation.github.io
repo_url: https://github.com/proactis-documentation/ExampleApplications
repo_name: CodeExamples
copyright: (C) PROACTIS Group Ltd - All Rights Reserved
site_author: David Betteridge
site_description: Technical documentation for the PROACTIS suite of products
extra_css:
    - css/extra.css
pages:
    - P2P:
        - 'Overview' : placeholder.md
        - 'Single Sign On (SSO)' : p2p/sso.md
        - 'Punchout' : placeholder.md
        - 'Invoice Posting' : placeholder.md
        - 'Budget Checking' : placeholder.md
        - 'Nominal Validation' : placeholder.md
        - 'Imaging Integration' : placeholder.md
        - 'Import APIs':
            - 'Invoices': p2p/overview.md
    - Spend Analytics: index.md
    - APF: 
        - 'overview' : apf/overview.md
        - 'p2p to apf' : apf/overview.md
        - 'Finance System to Payments Server' : apf/financesystem_to_paymentserver.md
    - S2C: placeholder.md
    - DueNorth: placeholder.md