site_name: Technical Documentation
site_dir: ../proactis-documentation.github.io
repo_url: https://github.com/proactis-documentation/ExampleApplications
repo_name: CodeExamples
copyright: (C) PROACTIS Group Ltd - All Rights Reserved
site_author: David Betteridge
site_description: Technical documentation for the PROACTIS suite of products
extra_css:
    - css/extra.css
pages:
    - PROACTIS: index.md
    - P2P:
        - 'Overview' : p2p/Placeholder.md
        - 'Single Sign On (SSO)' : p2p/sso.md
        - 'PunchOut / Marketplaces' : p2p/punchout.md
        - 'Nominal Validation' : p2p/nominalvalidation.md
        - 'Invoice Posting' : placeholder.md
        - 'Budget Checking' : placeholder.md
        - 'Imaging Integration' : placeholder.md
        - 'Import APIs':
            - 'Invoices': placeholder.md
    - Spend Analytics: placeholder.md
    - APF: 
        - 'overview' : apf/overview.md
        - 'p2p to apf' : apf/overview.md
        - 'Finance System to Payments Server' : apf/financesystem_to_paymentserver.md
    - S2C: s2c/placeholder.md
    - DueNorth: dueNorth/Placeholder.md


markdown_extensions:
    - admonition:
