site_name: proactis technical documentation
site_dir: ../proactis-documentation.github.io
pages:
    - P2P:
        - 'overview' : p2p/overview.md
        - 'Single Sign On (SSO)' : p2p/sso.md
        - 'Punchout' : p2p/overview.md
        - 'Invoice Posting' : p2p/overview.md
        - 'Budget Checking' : p2p/overview.md
        - 'Nominal Validation' : p2p/overview.md
        - 'Imaging Integration' : p2p/overview.md
        - 'Import APIs' : p2p/overview.md
    - Spend Analytics: index.md
    - APF: 
        - 'overview' : apf/overview.md
        - 'p2p to apf' : apf/overview.md
        - 'Finance System to Payments Server' : apf/financesystem_to_paymentserver.md
    - S2C: index.md
    - DueNorth: index.md