site_name: proactis technical documentation
site_dir: ../proactis-documentation.github.io
pages:
    - P2P: index.md
    - Spend Analytics: index.md
    - APF: 
        - 'overview' : apf/overview.md
        - 'p2p to apf' : apf/overview.md
        - 'Finance System to Payments Server' : apf/financesystem_to_paymentserver.md
    - S2C: index.md
    - DueNorth: index.md