site_name: Technical Documentation
site_dir: ../proactis-documentation.github.io
repo_url: https://github.com/proactis-documentation/ExampleApplications
repo_name: CodeExamples
copyright: (C) PROACTIS Group Ltd - All Rights Reserved
site_author: David Betteridge
site_description: Technical documentation for the PROACTIS suite of products
extra_css:
    - css/extra.css
pages:
    - PROACTIS: index.md
    - P2P:
        - 'Single Sign On (SSO)' : p2p/sso.md
        - 'PunchOut / Marketplaces' : p2p/punchout.md
        - 'Nominal Validation' : p2p/nominalvalidation.md
        - 'Budget Checking' : p2p/budgetchecking.md
        - 'Custom Tabs' : 'p2p/customtab.md'
        - 'Addins' : 'p2p/addins.md'        
        - 'Imaging Integration' :
            - 'Generic Imaging' : p2p/genericimaging.md
            - 'Custom Imaging' : p2p/customimaging.md
        # - 'Invoice Posting' : placeholder.md
        # - 'Commitment Posting' : placeholder.md
        # - 'Import APIs':
        #     - 'Invoices': placeholder.md
    - Spend Analytics: placeholder.md
    - APF: placeholder.md
    #     - 'overview' : apf/overview.md
    #     - 'p2p to apf' : apf/overview.md
    #     - 'Finance System to Payments Server' : apf/financesystem_to_paymentserver.md
    - S2C: placeholder.md
    - DueNorth: placeholder.md
    - System4: placeholder.md


markdown_extensions:
    - admonition:
